### ISSUE TITLE
Does not compile on recent versions of Delphi

### ISSUE THREAD

**Issue by JonathanLourens** [relativ/firemonkey-libvlc#1]
Hi Relativ,

I'm very interested in using your firemonkey wrapper for vlc. My only problem if that I use a more recent version of Delphi, and it does not compile. Most of the errors are related to TBitmap and the changes it has gotten. 

I've tried updating the code using TBitmap.Map to get pixeldata instead of TBitmap.startline.
I got it to compile now, but in designtime it only shows up as empty frame ( like TImage ).

When I initVlc, I can see the dll's being loaded in the debugger, but there's no vlc interface and no playing video.

I'm hoping this project is not dead, like to hear from you.
Kind regards,
Jonathan Lourens

**Comment by relativ** [comment]
it's only work with delphi xe 2
